onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -color Gray70 -radix decimal /tb_ComputeKernel/clk
add wave -noupdate -color Gray70 -radix decimal /tb_ComputeKernel/n_rst
add wave -noupdate -radix unsigned /tb_ComputeKernel/input_matrix
add wave -noupdate -radix unsigned /tb_ComputeKernel/kernel
add wave -noupdate -radix unsigned /tb_ComputeKernel/start
add wave -noupdate -radix unsigned -childformat {{{/tb_ComputeKernel/blurred_pixel[7]} -radix unsigned} {{/tb_ComputeKernel/blurred_pixel[6]} -radix unsigned} {{/tb_ComputeKernel/blurred_pixel[5]} -radix unsigned} {{/tb_ComputeKernel/blurred_pixel[4]} -radix unsigned} {{/tb_ComputeKernel/blurred_pixel[3]} -radix unsigned} {{/tb_ComputeKernel/blurred_pixel[2]} -radix unsigned} {{/tb_ComputeKernel/blurred_pixel[1]} -radix unsigned} {{/tb_ComputeKernel/blurred_pixel[0]} -radix unsigned}} -subitemconfig {{/tb_ComputeKernel/blurred_pixel[7]} {-height 16 -radix unsigned} {/tb_ComputeKernel/blurred_pixel[6]} {-height 16 -radix unsigned} {/tb_ComputeKernel/blurred_pixel[5]} {-height 16 -radix unsigned} {/tb_ComputeKernel/blurred_pixel[4]} {-height 16 -radix unsigned} {/tb_ComputeKernel/blurred_pixel[3]} {-height 16 -radix unsigned} {/tb_ComputeKernel/blurred_pixel[2]} {-height 16 -radix unsigned} {/tb_ComputeKernel/blurred_pixel[1]} {-height 16 -radix unsigned} {/tb_ComputeKernel/blurred_pixel[0]} {-height 16 -radix unsigned}} /tb_ComputeKernel/blurred_pixel
add wave -noupdate -color Cyan -radix unsigned /tb_ComputeKernel/done
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/blurred_pixel
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/contConv
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/readyFlag
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/end_column
add wave -noupdate -expand -group {Module Signals} -color Cyan -radix ufixed /tb_ComputeKernel/DUT/cur_x
add wave -noupdate -expand -group {Module Signals} -color Cyan -radix ufixed /tb_ComputeKernel/DUT/cur_y
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/done
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/end_row
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/input_matrix
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/kernel
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/SIZE
add wave -noupdate -expand -group {Module Signals} -radix ufixed /tb_ComputeKernel/DUT/start
add wave -noupdate -expand -group Accumulator -radix decimal /tb_ComputeKernel/DUT/get_accumulator/clk
add wave -noupdate -expand -group Accumulator -radix decimal /tb_ComputeKernel/DUT/get_accumulator/n_rst
add wave -noupdate -expand -group Accumulator -radix binary -childformat {{{/tb_ComputeKernel/DUT/get_accumulator/kernel_v[7]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/kernel_v[6]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/kernel_v[5]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/kernel_v[4]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/kernel_v[3]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/kernel_v[2]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/kernel_v[1]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/kernel_v[0]} -radix decimal}} -radixshowbase 1 -subitemconfig {{/tb_ComputeKernel/DUT/get_accumulator/kernel_v[7]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/kernel_v[6]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/kernel_v[5]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/kernel_v[4]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/kernel_v[3]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/kernel_v[2]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/kernel_v[1]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/kernel_v[0]} {-height 16 -radix decimal}} /tb_ComputeKernel/DUT/get_accumulator/kernel_v
add wave -noupdate -expand -group Accumulator -radix binary -radixshowbase 1 /tb_ComputeKernel/DUT/get_accumulator/pixel_v
add wave -noupdate -expand -group Accumulator -color Cyan -radix decimal /tb_ComputeKernel/DUT/get_accumulator/clear
add wave -noupdate -expand -group Accumulator -radix decimal /tb_ComputeKernel/DUT/get_accumulator/start
add wave -noupdate -expand -group Accumulator -radix decimal /tb_ComputeKernel/DUT/get_accumulator/ready
add wave -noupdate -expand -group Accumulator -radix decimal -childformat {{{/tb_ComputeKernel/DUT/get_accumulator/sum[7]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/sum[6]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/sum[5]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/sum[4]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/sum[3]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/sum[2]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/sum[1]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/sum[0]} -radix decimal}} -subitemconfig {{/tb_ComputeKernel/DUT/get_accumulator/sum[7]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/sum[6]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/sum[5]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/sum[4]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/sum[3]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/sum[2]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/sum[1]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/sum[0]} {-height 16 -radix decimal}} /tb_ComputeKernel/DUT/get_accumulator/sum
add wave -noupdate -expand -group Accumulator -color Cyan -radix decimal /tb_ComputeKernel/DUT/get_accumulator/state
add wave -noupdate -expand -group Accumulator -radix decimal /tb_ComputeKernel/DUT/get_accumulator/nextState
add wave -noupdate -expand -group Accumulator -radix decimal -childformat {{{/tb_ComputeKernel/DUT/get_accumulator/nextSum[15]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[14]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[13]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[12]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[11]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[10]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[9]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[8]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[7]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[6]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[5]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[4]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[3]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[2]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[1]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[0]} -radix decimal}} -subitemconfig {{/tb_ComputeKernel/DUT/get_accumulator/nextSum[15]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[14]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[13]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[12]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[11]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[10]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[9]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[8]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[7]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[6]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[5]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[4]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[3]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[2]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[1]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/nextSum[0]} {-height 16 -radix decimal}} /tb_ComputeKernel/DUT/get_accumulator/nextSum
add wave -noupdate -expand -group Accumulator -radix decimal -childformat {{{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[15]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[14]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[13]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[12]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[11]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[10]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[9]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[8]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[7]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[6]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[5]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[4]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[3]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[2]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[1]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[0]} -radix decimal}} -subitemconfig {{/tb_ComputeKernel/DUT/get_accumulator/bufferSum[15]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[14]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[13]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[12]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[11]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[10]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[9]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[8]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[7]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[6]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[5]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[4]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[3]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[2]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[1]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/bufferSum[0]} {-height 16 -radix decimal}} /tb_ComputeKernel/DUT/get_accumulator/bufferSum
add wave -noupdate -expand -group Accumulator -radix decimal /tb_ComputeKernel/DUT/get_accumulator/temp_kv
add wave -noupdate -expand -group Accumulator -radix decimal -childformat {{{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[15]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[14]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[13]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[12]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[11]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[10]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[9]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[8]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[7]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[6]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[5]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[4]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[3]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[2]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[1]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[0]} -radix decimal}} -subitemconfig {{/tb_ComputeKernel/DUT/get_accumulator/temp_pv[15]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[14]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[13]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[12]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[11]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[10]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[9]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[8]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[7]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[6]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[5]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[4]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[3]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[2]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[1]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/temp_pv[0]} {-height 16 -radix decimal}} /tb_ComputeKernel/DUT/get_accumulator/temp_pv
add wave -noupdate -expand -group Accumulator -radix decimal -childformat {{{/tb_ComputeKernel/DUT/get_accumulator/product[15]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[14]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[13]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[12]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[11]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[10]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[9]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[8]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[7]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[6]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[5]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[4]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[3]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[2]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[1]} -radix decimal} {{/tb_ComputeKernel/DUT/get_accumulator/product[0]} -radix decimal}} -subitemconfig {{/tb_ComputeKernel/DUT/get_accumulator/product[15]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[14]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[13]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[12]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[11]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[10]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[9]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[8]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[7]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[6]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[5]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[4]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[3]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[2]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[1]} {-height 16 -radix decimal} {/tb_ComputeKernel/DUT/get_accumulator/product[0]} {-height 16 -radix decimal}} /tb_ComputeKernel/DUT/get_accumulator/product
add wave -noupdate -expand -group Accumulator -radix decimal /tb_ComputeKernel/DUT/get_accumulator/nextProduct
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/clk
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/n_rst
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/cur_x
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/cur_y
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/kernel
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/in
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/en_strobe
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/kernel_v
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/pixel_v
add wave -noupdate -expand -group {Matrix Index} -radix decimal /tb_ComputeKernel/DUT/get_index/next_pixel_v
add wave -noupdate -expand -group {Matrix Index} /tb_ComputeKernel/DUT/get_index/next_kernel_v
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1148546 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1014528 ps} {1393972 ps}
